name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Check
        uses: actions/checkout@v2.3.2

      - name: Build Project
        run: ./gradlew assemble


