name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Run test
        run: ./gradlew testVariantNameUnitTest --tests '*.ExampleInstrumentedTest'

      - name: Build Project
        run: ./gradlew assemble


